export * from './titleResponse.dto';
export * from './titleParse.dto';
export * from './fieldsParse.dto';
export * from './wikiResponse.dto';
export * from './wikiParse.dto';
export * from './searchParse.dto';
export * from './searchResponse.dto';
export * from './imagesParse.dto';
export * from './imagesResponse.dto';
